name: Docker Build And Push To Aliyun Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout

      - name: Set up JDK 12.0
        uses: actions/setup-java@v1
        with:
          registry: ghcr.io 
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_IO_TOKEN }} 

      - name: Build with Gradle
        run: |
          dockerpull k8s.gcr.io/ingress-nginx/controller:v0.35.0 
          dockertag k8s.gcr.io/ingress-nginx/controller:v0.35.0 ghcr.io/zuoguocai/ingress-nginx/controller:v0.35.0 
          dockerpush ghcr.io/zuoguocai/ingress-nginx/controller:v0.35.0
